### ISSUE TITLE
Can you provide the codes for the baseline model?

### ISSUE THREAD

**Issue by ntubiolin** [nnzhan/MTGNN#10]
Hi!
I want to know how you implement the baselines. For example, I want to know if you use time_in_day only (w/o day_in_week) for GMAN and MRA-BGCN. Can you provide the codes for the baseline model? 

Thanks!

**Comment by nnzhan** [comment]
Hi, for GMAN the codes are here: https://github.com/zhengchuanpan/GMAN. for MRA-BGCN, you can ask the authors for codes.

Thanks.

**Comment by ntubiolin** [comment]
Ok, thanks for providing those info.
