### ISSUE TITLE
Reproduction of signal step forecasting on Solar 

### ISSUE THREAD

**Issue by cloudXia777** [nnzhan/MTGNN#13]
I use default parameters in signal step forecasting on Solar dataset. 10 average RSE (0.216), best RSE(0.20). There is a big gap between my result and performance in paper. Can u help me?

**Comment by cloudXia777** [comment]
solved

**Comment by aixiaodewugege** [comment]
Hi,i meet the same problem. Could u please tell me how did you fix it? Thank you!

**Comment by cloudXia777** [comment]
This is an auto vacation reply. Hi, I am on my works and may not reply in time. I will reply to you soon when I'm online.
