### ISSUE TITLE
Program Running Problem

### ISSUE THREAD

**Issue by zhp66** [nnzhan/MTGNN#17]
Hello, I configured the environment according to the configuration required by the program, but the program still can't run
begin training
Traceback (most recent call last):
  File "train_single_step.py", line 218, in <module>
    val_acc, val_rae, val_corr, test_acc, test_rae, test_corr = main()
  File "train_single_step.py", line 178, in main
    train_loss = train(Data, Data.train[0], Data.train[1], model, criterion, optim, args.batch_size)
  File "train_single_step.py", line 77, in train
    tx = X[:, :, id, :]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by kaisazhang** [comment]
Hello, how did you solve this problem？

**Comment by zixuanxuanxuanxuan** [comment]
我也遇到了同样的问题
