### ISSUE TITLE
About engine.py

### ISSUE THREAD

**Issue by sleeperzjf** [nnzhan/MTGNN#5]
Is `engine.py` used anywhere?

**Comment by nnzhan** [comment]
no, it isn't. I will delete it.

**Comment by sleeperzjf** [comment]
By the way, any chance that you can provide the `pickle` files too?
![image](https://user-images.githubusercontent.com/65698607/87400562-9110b880-c5eb-11ea-8bdb-d2d47d45c6eb.png)

**Comment by nnzhan** [comment]
Yes, please check the updates.

**Comment by sleeperzjf** [comment]
OK, Thanks a lot.
