### ISSUE TITLE
"buildA_true" in "train_single_step.py"

### ISSUE THREAD

**Issue by sleeperzjf** [nnzhan/MTGNN#6]
If you are going to provide a choice over `buildA_true`, you might as well add the type-changing codes to `train_single_step.py` as you did in `train_multi_step.py`:
![image](https://user-images.githubusercontent.com/65698607/87630269-4fa51800-c767-11ea-9f5f-24f697370cf6.png)
![image](https://user-images.githubusercontent.com/65698607/87630300-5a5fad00-c767-11ea-9cde-d35dc7d5cdd9.png)

**Comment by nnzhan** [comment]
thanks, we will improve it.
