### ISSUE TITLE
How to get the node locations

### ISSUE THREAD

**Issue by ntubiolin** [nnzhan/MTGNN#8]
Hi!
Thank you for providing the source codes and datasets for the great work.
However, I cannot find the node locations in the dataset  (e.g., longitude and latitude for each node)...
Can you tell me where to get the information? (I want to draw Fig. 6 (c) myself.)

Thanks!

**Comment by ntubiolin** [comment]
I think I find the location information in th [DCRNN](url) repo.

**Comment by 2326261098** [comment]
Hello, please ask which dataset you are looking for, have you found it, can you share it?
